language: node_js
before_script:
    - yarn
script:
    - yarn lint
    - yarn build
node_js:
    - "10.15.3"
cache:
    directories:
        -node_modules
branches:
    only:
        - master
notifications:
  email:
    on_success: never